name: Transform and Commit Output on Same Branch

on:
  # push:
  #   branches:
  #     - main
  #   paths:
  #     - 'app_config.json'

permissions:
  contents: write

jobs:
  transform-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install requests pillow

      - name: Run Python script with args
        run: |
          python transform_images.py app_config.json -o app_config_ems_img.json --indent 2

      - name: Commit app_config_ems_img.json if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if git diff --quiet app_config_ems_img.json; then
            echo "No changes to app_config_ems_img.json"
          else
            git add app_config_ems_img.json
            git commit -m "Update app_config_ems_img.json from transform_image.py"
            git push
          fi
